frontEnd:
    container:
        name: front-end
    image:
        pullPolicy: IfNotPresent
        repository: null
        tag: null
    replicaCount: 1
    resources:
        limits:
            cpu: 100m
            memory: 128Mi
        requests:
            cpu: 100m
            memory: 128Mi
    service:
        externalPort: 80
        internalPort: 80
        name: front-end
        type: ClusterIP
customerService:
    container:
        name: customer-service
    image:
        pullPolicy: IfNotPresent
        repository: null
        tag: null
    replicaCount: 1
    resources:
        limits:
            cpu: 100m
            memory: 128Mi
        requests:
            cpu: 100m
            memory: 128Mi
    service:
        externalPort: 8080
        internalPort: 8080
        name: customer-service
        type: ClusterIP
orderService:
    container:
        name: order-service
    image:
        pullPolicy: IfNotPresent
        repository: null
        tag: null
    replicaCount: 1
    resources:
        limits:
            cpu: 100m
            memory: 128Mi
        requests:
            cpu: 100m
            memory: 128Mi
    service:
        externalPort: 8080
        internalPort: 8080
        name: order-service
        type: ClusterIP
catalogService:
    container:
        name: catalog-service
    image:
        pullPolicy: IfNotPresent
        repository: robjahn/keptn-orders-catalog-service
        tag: 1
    replicaCount: 1
    resources:
        limits:
            cpu: 100m
            memory: 128Mi
        requests:
            cpu: 100m
            memory: 128Mi
    service:
        externalPort: 8080
        internalPort: 8080
        name: catalog-service
        type: ClusterIP
